[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "npx ts-node src/server-ts.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.build]
# Build TypeScript code
commands = ["npm install", "npm run build"] 