[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh -c 'find /app -name \"server-ts.ts\" && node --require ts-node/register $(find /app -name \"server-ts.ts\" | head -n 1)'"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.build]
# Skip TypeScript build in Railway and let Dockerfile handle it
commands = ["echo 'Using Dockerfile for build'"] 