[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node --require ts-node/register ./src/server-ts.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.build]
# Skip TypeScript build in Railway and let Dockerfile handle it
commands = ["echo 'Using Dockerfile for build'"] 